language: elixir
elixir: 1.2.3
addons:
  postgresql: "9.4"
services:
  - redis-server
otp_release:
  - 18.0
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
sudo: false
before_script:
  - mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
