language: elixir
elixir: 1.2.3
addons:
  postgresql: "9.4"
services:
  - redis-server
otp_release:
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aca35faec936cb8dd6e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

